export {default as OnBoarding} from './OnBoarding';
export {default as Home} from './Home';
export {default as Shop} from './Shop';
export {default as Cart} from './Cart';
export {default as ProductDetail} from './ProductDetail';
export {default as OrderDetail} from './OrderDetail';
export {default as Profile} from './Profile';
export {default as Login} from './Login';
export {default as SignUp} from './SignUp';